# threadsTBI Makefile

BUILD_DIR = build
SRC = UserTask # Edit here with your own UserTask file name

all: $(SRC).c
	-@mkdir $(BUILD_DIR)
	-@mkdir $(BUILD_DIR)/objects
	-@mkdir $(BUILD_DIR)/target
	arm-none-eabi-gcc $(SRC).c -ffunction-sections -o $(BUILD_DIR)/objects/$(SRC).o -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb
	arm-none-eabi-objcopy --output-format binary --only-section UserTask \
		$(BUILD_DIR)/objects/$(SRC).o $(BUILD_DIR)/target/$(SRC).bin